name: Create Release

on:
  push:
    tags:
      - "v*" # This workflow will run when any tag starting with 'v' is pushed

# Add permissions configuration
permissions:
  contents: write

jobs:
  build:
    name: Build and Create Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # We need full history to get commit messages

      - name: Install AutoHotkey v2
        run: |
          # Download AutoHotkey v2.0 runtime from GitHub releases
          $runtimeUrl = "https://github.com/AutoHotkey/AutoHotkey/releases/download/v2.0.18/AutoHotkey_2.0.18.zip"
          
          Write-Host "Downloading AutoHotkey v2.0.18 runtime..."
          Invoke-WebRequest -Uri $runtimeUrl -OutFile "ahk-runtime.zip" -UserAgent "Mozilla/5.0"
          
          # Extract the runtime
          Write-Host "Extracting AutoHotkey runtime..."
          Expand-Archive -Path "ahk-runtime.zip" -DestinationPath "AutoHotkey" -Force
          
          # Since the compiler isn't available as separate download, 
          # we need to install the full AutoHotkey package
          Write-Host "The compiler is not available separately, installing full AutoHotkey..."
          
          # Download the installer
          $installerUrl = "https://github.com/AutoHotkey/AutoHotkey/releases/download/v2.0.18/AutoHotkey_2.0.18_setup.exe"
          Invoke-WebRequest -Uri $installerUrl -OutFile "ahk_setup.exe" -UserAgent "Mozilla/5.0"
          
          # Install silently
          Start-Process -FilePath "ahk_setup.exe" -ArgumentList "/S" -Wait
          Start-Sleep -Seconds 10
          
          # Find installation and copy compiler to our AutoHotkey directory
          $installPaths = @(
            "C:\Program Files\AutoHotkey",
            "C:\Program Files (x86)\AutoHotkey"
          )
          
          foreach ($path in $installPaths) {
            $compilerPath = Join-Path $path "Compiler\Ahk2Exe.exe"
            if (Test-Path $compilerPath) {
              Write-Host "Found compiler at: $compilerPath"
              Copy-Item $compilerPath "AutoHotkey\Ahk2Exe.exe"
              break
            }
          }
          
          # Verify we have the necessary files
          if (Test-Path "AutoHotkey\AutoHotkey64.exe") {
            Write-Host "✓ AutoHotkey64.exe found"
          } else {
            Write-Error "AutoHotkey64.exe not found"
            exit 1
          }
          
          if (Test-Path "AutoHotkey\Ahk2Exe.exe") {
            Write-Host "✓ Ahk2Exe.exe found"
          } else {
            Write-Error "Ahk2Exe.exe not found"
            exit 1
          }
          
          Write-Host "AutoHotkey installation complete!"
        shell: powershell

      - name: Compile AutoHotkey Script
        run: |
          # Set paths
          $scriptPath = "key.ahk"
          $outputPath = "key.exe"
          $compilerPath = "AutoHotkey\Ahk2Exe.exe"
          $basePath = "AutoHotkey\AutoHotkey64.exe"
          
          # Verify files exist
          if (-not (Test-Path $scriptPath)) {
            Write-Error "Script file not found: $scriptPath"
            exit 1
          }
          
          if (-not (Test-Path $compilerPath)) {
            Write-Error "Compiler not found: $compilerPath"
            exit 1
          }
          
          if (-not (Test-Path $basePath)) {
            Write-Error "Base file not found: $basePath"
            exit 1
          }
          
          # Compile the script
          Write-Host "Compiling $scriptPath to $outputPath..."
          Write-Host "Using compiler: $compilerPath"
          Write-Host "Using base: $basePath"
          
          & $compilerPath /in $scriptPath /out $outputPath /base $basePath /compress 1
          
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Compilation failed with exit code $LASTEXITCODE"
            exit 1
          }
          
          if (Test-Path $outputPath) {
            Write-Host "Compilation successful! Output: $outputPath"
            $fileInfo = Get-Item $outputPath
            Write-Host "File size: $($fileInfo.Length) bytes"
          } else {
            Write-Error "Compiled executable not found"
            exit 1
          }
        shell: powershell

      - name: Get previous tag
        id: previoustag
        run: |
          echo "PREVIOUS_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo '')" >> $GITHUB_ENV
          echo "CURRENT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Generate release notes
        id: generate_notes
        run: |
          if [ -n "$PREVIOUS_TAG" ]; then
            echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
            echo "## Changes since $PREVIOUS_TAG" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            git log --pretty=format:"* %s (%an) [%h](https://github.com/${{ github.repository }}/commit/%H)" $PREVIOUS_TAG..$CURRENT_TAG >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
            echo "## Initial Release" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            git log --pretty=format:"* %s (%an) [%h](https://github.com/${{ github.repository }}/commit/%H)" >> $GITHUB_ENV
            echo "" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.CURRENT_TAG }}
          body: |
            ${{ env.RELEASE_NOTES }}

            ## Download

            - **key.exe** - Compiled AutoHotkey executable (Windows)
            - **Source code** - Download the source files to compile yourself

            ## Installation

            1. Download `key.exe` from the assets below
            2. Run the executable to start the AutoHotkey script

            ## Features

            - **Win+H/J/K/L**: Navigate between windows (vim-like)
            - **Win+Shift+H/L**: Switch virtual desktops with auto-focus
            - **Esc + combinations**: Comprehensive vim-like text navigation
          files: |
            key.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
